#! /bin/sh
############## Autostart ##############

bspc rule -r "*"

kill $(pgrep picom)
kill $(pgrep polybar)
kill $(pgrep sxhkd)
kill $(pgrep dunst)
kill $(pgrep autocutsel)

xrdb -load  ~/.cache/wal/colors.Xresources

sxhkd &
dunst &
numlockx &
autocutsel -s PRIMARY -fork &
wal -R &

bash ~/.config/polybar/launch.sh &
picom --config /home/kishan/.config/picom/picom.conf -b &
feh --bg-fill --no-fehbg ~/.config/wall.png &
xsetroot -cursor_name left_ptr &
xset r rate 400 44

##########################################


bspc monitor -d web code learn music movie social tools


####### Rules #######

bspc rule -a "Firefox"          	desktop="web" focus=on follow=on
bspc rule -a "Code - OSS"       	desktop='code' state=tiled split_dir=west split_ratio=0.66 focus=on
bspc rule -a "Postman"       		desktop='code'  focus=on
bspc rule -a "discord"            	desktop='social' state=pseudo_tiled follow=on
bspc rule -a "Hexchat"            	desktop='social' follow=on
bspc rule -a "mpv"                	desktop='movie' state=floating border=off follow=on
bspc rule -a "Spotify"            	desktop='music' state=pseudo_tiled follow=on focus=on
bspc rule -a "Lxappearance"       	desktop='tools' state=floating center=true focus=on
bspc rule -a "Thunar"             	desktop='tools' state=pseudo_tiled pseudo_tiled=on focus=on follow=on
bspc rule -a "File-roller"       	desktop='tools' state=floating center=true follow=on
bspc rule -a "feh"                	state=floating


######## Global Settings ########
bspc config automatic_scheme        alternate
bspc config pointer_modifier        shift
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

bspc config focus_follows_pointer   true


######## Borders and Gaps ########

bspc config border_radius        0
bspc config border_width         0
bspc config window_gap          10

bspc config bottom_padding       0
bspc config top_padding         33

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config click_to_focus      true

bspc config gapless_monocle       false
bspc config paddingless_monocle   false
bspc config single_monocle        true

bspc config normal_border_color     #2ecc71
bspc config active_border_color     #3498db
bspc config focused_border_color    #3498db
#bspc config presel_feedback_color   ${xrdb:color4:#222}
bspc config presel_border_color     #3498db
