#! /bin/sh
############## Autostart ##############
bspc rule -r "*"

kill $(pgrep picom)
kill $(pgrep polybar)
kill $(pgrep sxhkd)
kill $(pgrep dunst)
kill $(pgrep autocutsel)
kill $(pgrep polkit-gnome-authentication-agent-1)
kill $(pgrep xrandr)

xrdb -load  ~/.cache/wal/colors.Xresources &


if [ -x /home/kishan/.config/bspwm/xrand.sh ];then
  bash /home/kishan/.config/bspwm/xrand.sh &
fi

sxhkd &
dunst &S
numlockx &

/usr/libexec/polkit-gnome-authentication-agent-1  &
autocutsel -s PRIMARY -fork &

if [ -x /usr/bin/polybar ]; then
    bash $HOME/.config/polybar/launch.sh &
fi

picom --config /home/kishan/.config/picom/picom.conf -b &

polybar DP2 -c ~/.config/polybar/config.ini &
polybar DP0 -c ~/.config/polybar/config.ini &


wal -R &
feh --bg-scale --no-xinerama  ~/.config/wall.png &

xsetroot -cursor_name left_ptr &
xset r rate 400 44 &
xset mouse 3 6 &
##########################################



bspc monitor DP-2  -d  chromium code learn music movie
bspc monitor DP-0  -d  firefox social

####### Rules #######

bspc rule -a "Firefox"            	    desktop="firefox" focus=on follow=on
bspc rule -a "discord"            	    desktop='social' state=floating follow=on border=off
bspc rule -a "Hexchat"            	    desktop='social' follow=on
bspc rule -a "mpv"                	    desktop='movie' state=floating center=true border=off follow=on focus=on
bspc rule -a "Spotify"            	    desktop='music' state=pseudo_tiled border=off follow=on focus=on
bspc rule -a "Lxappearance"       	    state=floating center=true focus=on follow=on
bspc rule -a "Thunar"             	    state=floating focus=on follow=on border=off
bspc rule -a "File-roller"       	      state=floating center=true follow=on
bspc rule -a "feh"                	    state=floating follow=on
bspc rule -a "kitty"                    state=pseudo_tiled follow=on
bspc rule -a "VSCodium"         	  	  desktop='code' focus=on follow=on
bspc rule -a "Postman"        	  	    desktop='code' focus=on follow=on

######## Global Settings ########
bspc config automatic_scheme        spiral
bspc config pointer_modifier        mod
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

bspc config focus_follows_pointer   true

######## Borders and Gaps ########

bspc config border_radius       50
bspc config border_width         1
bspc config window_gap          10

bspc config bottom_padding       0
bspc config top_padding         30

bspc config split_ratio         0.50
bspc config borderless_monocle            true
bspc config click_to_focus                true
bspc config history_aware_focus           true

bspc config gapless_monocle       false
bspc config paddingless_monocle   false
bspc config single_monocle        true

bspc config normal_border_color   \#5e4f77
bspc config active_border_color   \#9e70a1
bspc config focused_border_color  \#9e70a1
bspc config presel_feedback_color \#d15a6e


